# Navigation Links
#   To link a homepage section, use a hash `#` followed by the section ID.
#   The weight parameter defines the order that the links appear.

main:
  - name: Projects and Publications
    url: /#projects
    weight: 10
  - name: Technical Toolkit
    url: /#skills
    weight: 20
  - name: Education and Work Experience
    url: /#experience
    weight: 30
  - name: Blog
    url: /#blog
    weight: 40
  - name: Research Talks
    url: /#talks
    weight: 50
  - name: Gallery
    url: /#gallery
    weight: 60
  - name: Contact Me
    url: /#contact
    weight: 70
